version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=postgresql://app:app@db:5432/rth?serverVersion=15&charset=utf8
      - APP_ENV=dev
      - APP_SECRET=abcdef1234567890
      - MAILER_DSN=smtp://mailhog:1025
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: rth
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port

volumes:
  db_data:
