<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260430141132 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE test_case (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, project_id INT NOT NULL, test_suite_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D71B3CB166D1F9C ON test_case (project_id)');
        $this->addSql('CREATE INDEX IDX_7D71B3CBDA9FBE4E ON test_case (test_suite_id)');
        $this->addSql('CREATE TABLE test_suite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1EE2422D166D1F9C ON test_suite (project_id)');
        $this->addSql('ALTER TABLE test_case ADD CONSTRAINT FK_7D71B3CB166D1F9C FOREIGN KEY (project_id) REFERENCES "project" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE test_case ADD CONSTRAINT FK_7D71B3CBDA9FBE4E FOREIGN KEY (test_suite_id) REFERENCES test_suite (id)');
        $this->addSql('ALTER TABLE test_suite ADD CONSTRAINT FK_1EE2422D166D1F9C FOREIGN KEY (project_id) REFERENCES "project" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE test_case DROP CONSTRAINT FK_7D71B3CB166D1F9C');
        $this->addSql('ALTER TABLE test_case DROP CONSTRAINT FK_7D71B3CBDA9FBE4E');
        $this->addSql('ALTER TABLE test_suite DROP CONSTRAINT FK_1EE2422D166D1F9C');
        $this->addSql('DROP TABLE test_case');
        $this->addSql('DROP TABLE test_suite');
    }
}
