<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260430155552 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, original_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, file_size INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, requirement_id INT DEFAULT NULL, bug_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_795FD9BB7B576F77 ON attachment (requirement_id)');
        $this->addSql('CREATE INDEX IDX_795FD9BBFA3DB3D5 ON attachment (bug_id)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BB7B576F77 FOREIGN KEY (requirement_id) REFERENCES requirement (id)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BBFA3DB3D5 FOREIGN KEY (bug_id) REFERENCES bug (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attachment DROP CONSTRAINT FK_795FD9BB7B576F77');
        $this->addSql('ALTER TABLE attachment DROP CONSTRAINT FK_795FD9BBFA3DB3D5');
        $this->addSql('DROP TABLE attachment');
    }
}
