<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260430150304 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bug (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, summary VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, severity VARCHAR(50) NOT NULL, priority VARCHAR(50) NOT NULL, project_id INT NOT NULL, requirement_id INT DEFAULT NULL, test_case_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_358CBF14166D1F9C ON bug (project_id)');
        $this->addSql('CREATE INDEX IDX_358CBF147B576F77 ON bug (requirement_id)');
        $this->addSql('CREATE INDEX IDX_358CBF141351003D ON bug (test_case_id)');
        $this->addSql('ALTER TABLE bug ADD CONSTRAINT FK_358CBF14166D1F9C FOREIGN KEY (project_id) REFERENCES "project" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bug ADD CONSTRAINT FK_358CBF147B576F77 FOREIGN KEY (requirement_id) REFERENCES requirement (id)');
        $this->addSql('ALTER TABLE bug ADD CONSTRAINT FK_358CBF141351003D FOREIGN KEY (test_case_id) REFERENCES test_case (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bug DROP CONSTRAINT FK_358CBF14166D1F9C');
        $this->addSql('ALTER TABLE bug DROP CONSTRAINT FK_358CBF147B576F77');
        $this->addSql('ALTER TABLE bug DROP CONSTRAINT FK_358CBF141351003D');
        $this->addSql('DROP TABLE bug');
    }
}
